apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dufs.fullname" . }}
  labels:
    {{- include "dufs.labels" . | nindent 4 }}
data:
  dufs.yaml : |
    serve-path: '/dufs/data'
    bind: 0.0.0.0
    port: 5000
    auth: []
    allow-all: false
    allow-upload: true
    allow-delete: true
    allow-search: true
    allow-symlink: true
    allow-archive: true
    enable-cors: true
    render-index: true
    render-try-index: true
    render-spa: true
    log-format: '$remote_addr "$request" $status $http_user_agent'
    log-file: /dev/stdout
    compress: low
